version: '3'

services:
  nginx:
    build:
      context: ./requirements
      dockerfile: nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      # Bind mount the Nginx configuration directory on the host to the directory in the container
      # ensuring that any changes made to files on the host will be reflected in the container
      # The nginx package changed the default location for vhosts from conf.d/ to http.d.
      - ./requirements/nginx/conf:/etc/nginx/http.d/
      # Mount certificates and keys for the domain to the appropriate directory on the container
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      # Mount the WordPress application code tothe directory set as root in the Nginx server block
      - wp-volume:/var/www/html
    restart: unless-stopped

  mariadb:
    build:
      context: ./requirements
      dockerfile: mariadb/Dockerfile
      args:
      # Pull values from the .env file (Makefile: --env-file)
        DB_NAME: ${DB_NAME} 
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
        DB_HOST: ${DB_HOST}
        DB_MAIL: ${DB_MAIL}
        DB_TITLE: ${DB_TITLE}
        DB_URL: ${DB_URL}
        DOMAIN_NAME: ${DOMAIN_NAME}
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    user: mysql
    restart: unless-stopped

  wordpress:
    build:
      context: ./requirements
      dockerfile: wordpress/Dockerfile 
    env_file:
      - .env
    environment:
    # Pull values from the .env file (Makefile: --env-file)
      - DB_NAME
      - DB_USER
      - DB_PASS
      - DB_ROOT
      - DB_HOST
      - DB_MAIL
      - DB_TITLE
      - DB_URL
      - WP_NAME
      - WP_PASS
      - WP_MAIL
      - DOMAIN_NAME
    container_name: wordpress
    depends_on:
      - mariadb
    restart: on-failure
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/html

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
  inception:
    driver: bridge
